# Generated by Django 2.2.16 on 2022-03-09 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20220308_1836'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='review',
            name='review_unique',
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('author', 'title'), name='review_unique'),
        ),
    ]
