# Generated by Django 2.2.16 on 2022-03-09 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20220309_1745'),
        ('reviews', '0005_auto_20220309_1439'),
    ]

    operations = [
    ]
